site_name: Django Post-fetch Hook
site_description: Adds a post-fetch hook to Django models, which can be used to modify data fetched from database via the Django ORM.

nav:
  - Home: index.md
  - Usage: usage.md

theme:
  name: readthedocs
  highlightjs: false  # Use pygments instead.

markdown_extensions:
  pymdownx.highlight:
    anchor_linenums: true
    linenums: true
  pymdownx.inlinehilite:
  pymdownx.blocks.details:
  pymdownx.snippets:
    base_path: docs/snippets
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:mermaid2.fence_mermaid
  toc:
    permalink: 🔗

plugins:
  - search:
  - mermaid2:
      version: 10.2.4

extra_css:
  - css/docs.css
  - css/pygments.css
