# Generated by Django 4.2.1 on 2023-05-24 20:02

import django.db.models.deletion
from django.db import migrations, models

import post_fetch_hook.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Object",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=(post_fetch_hook.mixins.PostFetchModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Thing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, null=True)),
                ("age", models.IntegerField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=(post_fetch_hook.mixins.PostFetchModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=20, null=True)),
                (
                    "obj",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parents",
                        to="myapp.object",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=(post_fetch_hook.mixins.PostFetchModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="object",
            name="thing",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="objs", to="myapp.thing"),
        ),
    ]
